In [9]:
import sympy as sp
import numpy as np

In [26]:
x = sp.Symbol('x')
y = sp.Symbol('y')
f = x**2 - x**3 + 5 + y**4
sp.diff(f, x).subs(x, 5)
f.subs({x: 1, y:2})


21

In [33]:
dict(zip([1,2,3],[2,3,4]))

{1: 2, 2: 3, 3: 4}

In [20]:
a = np.array([1,2,3,7])
b = np.array([3,4,5,6])
sum([_**2 for _ in b]+a)>1 == True

True

In [74]:
x_1, x_2, x_3 = sp.Symbol('x_1'), sp.Symbol('x_2'), sp.Symbol('x_3')
X = [x_1, x_2, x_3]
f = 5*x_1**2 + 2*x_2**2 + 5*x_3**2 - 2*x_1*x_2 - 4*x_1*x_3 - 2*x_3 + 1
l = 0.1
e = 0.0001 
x0 = np.array([0, 0, 0])
res = []
x0 - l*np.array([sp.diff(f, X[i]).subs(dict(zip(X, x0))) for i in range(len(X))])
while True:
    x1 = x0 - l*np.array([sp.diff(f, X[i]).subs(dict(zip(X, x0))) for i in range(len(X))])
    print(x1)
    res.append([x0, f.subs(dict(zip(X, x0)))])
    print(abs(sum(x1-x0)))
    if abs(sum(x1 - x0)) < e:
        break
    x0 = x1
res

[0 0 0.200000000000000]
0.200000000000000
[0.0800000000000000 0 0.200000000000000]
0.0800000000000000
[0.0800000000000000 0.0160000000000000 0.232000000000000]
0.0480000000000000
[0.0960000000000000 0.0256000000000000 0.232000000000000]
0.0256000000000000
[0.0979200000000000 0.0345600000000000 0.238400000000000]
0.0172800000000000
[0.102272000000000 0.0403200000000000 0.239168000000000]
0.0108800000000000
[0.103731200000000 0.0446464000000000 0.240908800000000]
0.00752640000000003
[0.105292800000000 0.0475340800000000 0.241492480000000]
0.00503295999999996
[0.106103808000000 0.0495790080000000 0.242117120000000]
0.00348057599999999
[0.106762649600000 0.0509681664000000 0.242441523200000]
0.00237240319999999
[0.107170242560000 0.0519334297600000 0.242705059840000]
0.00163639296000004
[0.107468709888000 0.0525941063680000 0.242868097024000]
0.00112218111999996
[0.107666060083200 0.0530502057984000 0.242987483955200]
0.000772836556800015
[0.107805034741760 0.0533633354956800 0.24306642403

[[array([0, 0, 0]), 1],
 [array([0, 0, 0.200000000000000], dtype=object), 0.800000000000000],
 [array([0.0800000000000000, 0, 0.200000000000000], dtype=object),
  0.768000000000000],
 [array([0.0800000000000000, 0.0160000000000000, 0.232000000000000],
        dtype=object),
  0.760832000000000],
 [array([0.0960000000000000, 0.0256000000000000, 0.232000000000000],
        dtype=object),
  0.758507520000000],
 [array([0.0979200000000000, 0.0345600000000000, 0.238400000000000],
        dtype=object),
  0.757558476800000],
 [array([0.102272000000000, 0.0403200000000000, 0.239168000000000],
        dtype=object),
  0.757131902976000],
 [array([0.103731200000000, 0.0446464000000000, 0.240908800000000],
        dtype=object),
  0.756933575966720],
 [array([0.105292800000000, 0.0475340800000000, 0.241492480000000],
        dtype=object),
  0.756840305315021],
 [array([0.106103808000000, 0.0495790080000000, 0.242117120000000],
        dtype=object),
  0.756796268667208],
 [array([0.106762649600