In [1]:
import sympy as sp
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [130]:
# np.random.seed(14)
x_1, x_2, x_3 = sp.Symbol('x_1'), sp.Symbol('x_2'), sp.Symbol('x_3')
X = [x_1, x_2, x_3]
f = 5*x_1**2 + 2*x_2**2 + 5*x_3**2 - 2*x_1*x_2 - 4*x_1*x_3 - 2*x_3 + 1
l = 0.01
e = 0.00001 
x0 = np.array([0, 0, 0])
res = []
while True:
    x_rand_i = np.random.randint(0, len(X))
    x1 = x0 - l*np.array([sp.diff(f, X[i]).subs(dict(zip(X, x0))) if i == x_rand_i else 0 for i in range(len(X))])
    print(l*np.array([sp.diff(f, X[i]).subs(dict(zip(X, x0))) if i == x_rand_i else 0  for i in range(len(X))]), sum([abs(_) for _ in (x1 - x0)]))
    res.append([x0, f.subs(dict(zip(X, x0)))])
    if sum([abs(_) for _ in (x1 - x0)]) < e and (f.subs(dict(zip(X, x1))) - f.subs(dict(zip(X, x0)))) < e:
        break
    x0 = x1
res

[0.0 0.0 -0.0200000000000000] 0.0200000000000000
[0.0 0.0 -0.0180000000000000] 0.0180000000000000
[-0.00152000000000000 0.0 0.0] 0.00152000000000000
[0.0 0.0 -0.0162608000000000] 0.0162608000000000
[-0.00201843200000000 0.0 0.0] 0.00201843200000000
[0.0 0.0 -0.0147154572800000] 0.0147154572800000
[0.0 -7.07686400000000e-5 0.0] 7.07686400000000e-5
[0.0 -6.79378944000000e-5 0.0] 6.79378944000000e-5
[-0.00240798122188800 0.0 0.0] 0.00240798122188800
[0.0 0.0 -0.0133402308008755] 0.0133402308008755
[0.0 -0.000113380003061760 0.0] 0.000113380003061760
[-0.00270305993179546 0.0 0.0] 0.00270305993179546
[0.0 0.0 -0.0121143301180598] 0.0121143301180598
[0.0 -0.000162906001575199 0.0] 0.000162906001575199
[0.0 0.0 -0.0109028971062538] 0.0109028971062538
[0.0 0.0 -0.00981260739562843] 0.00981260739562843
[-0.00374920544344510 0.0 0.0] 0.00374920544344510
[-0.00337428489910059 0.0 0.0] 0.00337428489910059
[-0.00303685640919053 0.0 0.0] 0.00303685640919053
[0.0 -0.000359596696546915 0.0] 0.0003595

[[array([0, 0, 0]), 1],
 [array([0.0, 0.0, 0.0200000000000000], dtype=object), 0.962000000000000],
 [array([0.0, 0.0, 0.0380000000000000], dtype=object), 0.931220000000000],
 [array([0.00152000000000000, 0.0, 0.0380000000000000], dtype=object),
  0.931000512000000],
 [array([0.00152000000000000, 0.0, 0.0542608000000000], dtype=object),
  0.905881218419200],
 [array([0.00353843200000000, 0.0, 0.0542608000000000], dtype=object),
  0.905494181984031],
 [array([0.00353843200000000, 0.0, 0.0689762572800000], dtype=object),
  0.884922437102878],
 [array([0.00353843200000000, 7.07686400000000e-5, 0.0689762572800000],
        dtype=object),
  0.884921946299238],
 [array([0.00353843200000000, 0.000138706534400000, 0.0689762572800000],
        dtype=object),
  0.884921493974603],
 [array([0.00594641322188800, 0.000138706534400000, 0.0689762572800000],
        dtype=object),
  0.884370648485932],
 [array([0.00594641322188800, 0.000138706534400000, 0.0823164880808755],
        dtype=object),
  0.8

In [131]:
def stohastic_gradient_descent(
    variable: list,
    f,
    x0: np.ndarray = np.array([]),
    /,
    step: float=0.01,
    error: float=0.000000001,
    itteration: int=100,
) -> str:
    '''Ванильный градиентный спуск с заданным шагом h'''
    if len(x0) != len(variable):
        return 'Размерность начальной точки не корректна'
    X = list(map(sp.Symbol, variable))
    x0 = np.array(x0) 
    res = []
    i = 0
    np.random.seed(14)
    while True:
        x_rand_i = np.random.randint(0, len(X))
        x1 = x0 - step*np.array([sp.diff(f, X[i]).subs(dict(zip(X, x0))) if i == x_rand_i else 0 for i in range(len(X))])
        if sum([abs(_) for _ in (x1 - x0)]) < error and (f.subs(dict(zip(X, x1))) - f.subs(dict(zip(X, x0)))) < error:
            res.append([x0, f.subs(dict(zip(X, x0)))])
            return f'Приблеженные значения точки минимума: {res[0][0]} со значением {res[0][1]}, с точностью до погрешности {error}'
        x0 = x1
        i += 1
        if i > itteration:
            return f'Число иттераций превысило {itteration}'
        

In [133]:
stohastic_gradient_descent(['x_1', 'x_2', 'x_3'], 5*x_1**2 + 2*x_2**2 + 5*x_3**2 - 2*x_1*x_2 - 4*x_1*x_3 - 2*x_3 + 1, [0,0,0])

'Приблеженные значения точки минимума: [0 0 0] со значением 1, с точностью до погрешности 1e-09'